version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "5002:80"
      - "4433:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
volumes:
  kanboard_data:
  kanboard_plugins:
