version: "3.7"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - caddynet

volumes:
  caddy_data:
  caddy_config:

networks:
  caddynet:
    external: true
